name: build
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: short-sha
      uses: hudsonm62/short-sha@v1
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Test
      run: go test -v ./...
    - name: Vet
      run: go vet  ./...
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build linux
      run: go build -ldflags "-X 'main.version=${{ steps.short-sha.outputs.sha }}'" -o zabbix-http
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            zabbix-http
    - name: show files
      run: ls
    - name: Build and Push Latest Docker Image
      id: build-and-push-latest
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        build-args: |
          "APP_VERSION=${{ steps.short-sha.outputs.sha }}"
          "ENTRYPOINT=entrypoint"
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}